gitlab ci config added
diffblue/java-demo pull request #22
Opened 2018-10-03 17:29 UTC by ryanbarwick

2018-10-04 09:43 UTC, JohnLBergqvist approved these changes

2018-10-04 10:03 UTC, rjmunro requested changes
Please add some comments.

2018-10-09 17:03 UTC, rjmunro approved these changes

2018-10-10 11:56 UTC, royletron approved these changes

2018-10-10 14:29 UTC, merged