Add maven-surefile-plugin
diffblue/java-demo pull request #26
Opened 2018-11-09 08:49 UTC by yumibagge

The maven-surefile-plugin is now needed to perform maven test due to a
bug in the openjdk-8 package.

2018-11-09 08:57 UTC, yumibagge commented
I have tested `mvn test` on local and also on platform by cloning the branch.

2018-11-09 09:44 UTC, paulkennethkent commented
@yumibagge did you replicate this issue on platform or locally?

2018-11-09 09:51 UTC, yumibagge commented
@paulkennethkent, the issue is reproducible on local. Sorry, I was not stating the test I performed before requesting... Tests I conducted are
- run `mvn test `on my branch java-demo
- zip the java-demo, uploaded to platform,  downloaded tests, then run `mvn test` on local.
- create project from java-demo/branch, downloaded tests, then run `mvn test` on local.
Does it answer your question?

2018-11-09 12:28 UTC, jgwilson42 requested changes
Just one question.

2018-11-10 11:32 UTC, yumibagge commented on pom.xml
> +  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
I don't think the change is necessary. I think what had happen was I reformatted using IntellJ checkstyle plugin (based on google style), it reformatted this way. I am happy to return to the original if you think the original format is better.

2018-11-14 08:35 UTC, paulkennethkent approved these changes

2018-11-14 08:35 UTC, paulkennethkent commented on pom.xml
> +  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
We try to conform to Google coding standard so this seems like a logical change?

2018-11-20 19:18 UTC, jgwilson42 approved these changes

2018-11-20 20:16 UTC, merged